#!/bin/sh
unset LUA_PATH LUA_PATH_5_2 LUA_PATH_5_3 LUA_PATH_5_4
LUAROCKS_SYSCONFDIR="/usr/local/etc/luarocks" LUA_PATH="/home/ubuntu/workspace/luarocks-3.0.3/src/?.lua;;" exec "/usr/bin/lua5.2" "/home/ubuntu/workspace/luarocks-3.0.3/src/bin/luarocks" --project-tree="/home/ubuntu/workspace/luarocks-3.0.3/lua_modules" "$@"
